In [1]:
# CTL Central Limit Theorem

In [73]:
from scipy import stats
import statistics
import pandas as pd

In [3]:
# 1. random distribution 
# 2. mean == median 
# 3. take sample from population 
# 4. taken sample also a normal distribution 
# 5. sample mean =. pop- mean 

In [4]:
import numpy as np

In [30]:
pop_values = np.random.normal(loc = 20, scale = 2, size = 100)

In [31]:
pop_values

array([25.45381936, 20.54969261, 19.80302945, 22.88979795, 18.48026036,
       19.14139042, 20.44498569, 22.34993408, 20.32655038, 18.28739661,
       18.61462065, 21.52778032, 19.43373872, 23.60628205, 22.03047216,
       17.85369732, 20.20272272, 20.09768359, 17.67270658, 22.66843456,
       19.56850978, 22.15068674, 18.62282267, 19.93660344, 21.7470671 ,
       22.6797121 , 24.41558488, 18.37607746, 19.20545251, 20.57287955,
       18.59190736, 18.50597686, 17.54477511, 23.11297927, 22.39495467,
       21.83713107, 23.2672422 , 17.97333798, 22.68840617, 18.2821173 ,
       21.73540985, 19.53100724, 20.12499465, 22.3836689 , 17.82074986,
       27.64570235, 19.09103864, 20.25882025, 23.65414338, 15.95666838,
       22.62558327, 18.48194465, 16.65551347, 20.95490039, 21.96661665,
       21.31538142, 21.80084558, 16.08399193, 19.99254445, 17.80926371,
       21.3005308 , 20.74982564, 14.8896256 , 16.64060097, 17.78036815,
       19.52160131, 15.21895653, 22.64375532, 21.0923494 , 17.78

In [35]:
# Finding pop mean value 

np.mean(pop_values)

19.846347579874276

In [36]:
# Finding the median value of population 

np.median(pop_values)

19.878131877517447

In [26]:
# confirmed population is normally distributed

In [27]:
# Selecting or picking random values from population 

In [37]:
sample_data = np.random.choice(pop_values, size = 30, replace = False)

In [38]:
sample_data

array([17.82074986, 18.48026036, 20.95971848, 19.53100724, 17.78036815,
       23.2672422 , 20.54969261, 23.11297927, 20.57287955, 19.22127716,
       17.67270658, 17.80926371, 14.8896256 , 18.2821173 , 16.69149928,
       19.30459854, 27.64570235, 21.7470671 , 21.80084558, 20.95490039,
       19.99254445, 20.44498569, 20.19919761, 22.15068674, 18.37607746,
       21.3005308 , 20.81555721, 17.79795757, 22.68840617, 19.79693844])

In [39]:
len(sample_data)

30

In [40]:
np.mean(sample_data)

20.05524611518364

In [41]:
# Variance and Std

In [42]:
sample_data

array([17.82074986, 18.48026036, 20.95971848, 19.53100724, 17.78036815,
       23.2672422 , 20.54969261, 23.11297927, 20.57287955, 19.22127716,
       17.67270658, 17.80926371, 14.8896256 , 18.2821173 , 16.69149928,
       19.30459854, 27.64570235, 21.7470671 , 21.80084558, 20.95490039,
       19.99254445, 20.44498569, 20.19919761, 22.15068674, 18.37607746,
       21.3005308 , 20.81555721, 17.79795757, 22.68840617, 19.79693844])

In [43]:
np.var(sample_data)

5.76627120125715

In [44]:
np.std(sample_data)

2.40130614484225

In [50]:
val = [1,2,3,4,5, 60]

In [51]:
np.var(val)

452.9166666666667

In [52]:
np.mean(val)

12.5

In [53]:
np.median(val)

3.5

In [54]:
# var, std, normal dist, outlier 

# Hypo

In [55]:
# Univariate selection -> One of the feature selection meathod

correlation -> continious variables

3 types of testing 

1. ttest                --> continious to continious | cat to cat 
2. chi-squre test       --> cat to cat 
3. ANOVA test (one way) --> cat to continious 



Types of Hypothysis

1. Null Hypothysis ---> 2 features are getting more correleated or there is no significent different
2. Alternative Hypothysis --->  there is a significent different between two columns or features


Reject null hypothysis ==== Alternative Hypothysis

Accept null hypothysis ==== Null Hypothysis

-------------------------------------------------------------------------------------------------------------------

p-value => you will get it from all types of testing , ttest, chi, anova 

p-value => 0 to 1

p-value threshold value => 0.05   => 5 %


if p-vale < 0.05:
    
    reject null hypothysis
    Alternative Hypothysis
    there is a significent different between two columns


if p-value > 0.05:

    accept null hypothysis
    there is no difference between columns or features
    
    






In [74]:
data = pd.read_csv("data.csv")

# Hypothysis

In [ ]:
# t = (x - mean) / (std / sqrt(n))

In [60]:
feat_1 = [1,2,3,4,5]

feat_2 = [2,5,8,9,11]

In [63]:
_, p_value = stats.ttest_ind(feat_1, feat_2)

In [66]:
stats.ttest_ind(feat_1, feat_2)

Ttest_indResult(statistic=-2.3094010767585034, pvalue=0.04973556311940192)

In [64]:
p_value

0.04973556311940192

In [67]:
p_value < 0.05

True

In [71]:
def check_hypo(p):
    if p < 0.05:

        print("Reject Null Hypothysis \nThere is a diff bw both features")
    else:
        print("Accept Null Hypothysis \nThere is no diff bw both features")

In [72]:
check_hypo(p_value)

Reject Null Hypothysis 
There is a diff bw both features


In [75]:
data.head()

Education  JoiningYear       City  PaymentTier  Age   Sal  Gender  \
0  Bachelors         2017  Bangalore            3   34  3400    Male   
1  Bachelors         2013       Pune            1   28  2800  Female   
2  Bachelors         2014  New Delhi            3   38  3800  Female   
3    Masters         2016  Bangalore            3   27  2700    Male   
4    Masters         2017       Pune            3   24  2400    Male   

  EverBenched  ExperienceInCurrentDomain  LeaveOrNot  
0          No                          0           0  
1          No                          3           1  
2          No                          2           0  
3          No                          5           1  
4         Yes                          2           1

In [76]:
stats.ttest_ind(data['JoiningYear'], data['Age'])

Ttest_indResult(statistic=26182.058423038066, pvalue=0.0)

In [77]:
# Cont and Cata

In [78]:
# male -> sal    |
# female -> sal  |. comparing or finding relationship bw both male and female sal

In [81]:
mal_sal = data[data['Gender']=='Male']['Sal']
fem_sal = data[data['Gender']=='Female']['Sal']

In [93]:
_, p_value = stats.f_oneway(mal_sal, fem_sal)

In [94]:
p_value

0.7920786580742085

In [95]:
check_hypo(p_value)

Accept Null Hypothysis 
There is no diff bw both features


In [96]:
# Chi2 test 

In [97]:
f1 = [1,1,1,1,0,0,1,1]
f2 = [0,1,0,1,1,1,0,0]

In [98]:
df = pd.DataFrame({
    "c1": f1,
    "c2": f2
})

In [99]:
df

c1  c2
0   1   0
1   1   1
2   1   0
3   1   1
4   0   1
5   0   1
6   1   0
7   1   0

In [100]:
# c2 = (OV- EV) / EV # OV- Observed Value, EV - Expected Value

In [101]:
stats.chi2_contingency(df)

Chi2ContingencyResult(statistic=5.833333333333334, pvalue=0.5593395827820361, dof=7, expected_freq=array([[0.6, 0.4],
       [1.2, 0.8],
       [0.6, 0.4],
       [1.2, 0.8],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.6, 0.4]]))

In [102]:
_, p_value, _,_ = stats.chi2_contingency(df)

In [103]:
p_value

0.5593395827820361

In [104]:
check_hypo(p_value)

Accept Null Hypothysis 
There is no diff bw both features


In [105]:
# Covariance 

In [106]:
# cov. = (x- mean of x) (y - mean of y)    /     N       -> population covariance 
# cov. = (x- mean of x) (y - mean of y)    /     N - 1   -> sample covariance

In [107]:
a = [1,2,3,4,5,6,7]
b = [7,6,5,4,3,2,1]

In [119]:
v1 = np.cov(a,b)

In [120]:
v1

array([[ 4.66666667, -4.66666667],
       [-4.66666667,  4.66666667]])

In [121]:
v1 = v1/4.66666667

In [122]:
v1

array([[ 1., -1.],
       [-1.,  1.]])

In [123]:
v1[0,1]

-0.9999999992857143

In [124]:
"""Example : 2
    """


a = [1,2,3,4,5,6,7]
b = [7,6,7,4,1,2,1]

In [126]:
np.cov(a, b)/ 7.3

array([[ 0.63926941, -0.73059361],
       [-0.73059361,  1.00456621]])

In [130]:
np.cov(data['Age'], data['JoiningYear'])/23.291115819655374

array([[1.        , 0.00508319],
       [0.00508319, 0.14907715]])

In [131]:
# rough